# fly.toml app configuration file generated for job-application-dashboard on 2024-03-06T14:30:25+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-application-dashboard'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
